/* eslint-disable @typescript-eslint/no-explicit-any */
import { FastifyInstance } from "fastify";
import fp from "fastify-plugin";
import fastifySwagger from "@fastify/swagger";
import fastifySwaggerUi from "@fastify/swagger-ui";

import { getServerVersion } from "../utils/utils.js";
import { APP_ENV } from "../common/enum.js";

async function swaggerPlugin(fastify: FastifyInstance): Promise<void> {
  const version = await getServerVersion();

  await fastify.register(fastifySwagger, {
    openapi: {
      info: {
        title: "Fastify API docs",
        description: "OpenApi v3 documentation",
        version,
        contact: {
          name: "API Support",
          email: "filippomeniswork@gmail.com",
        },
      },
      externalDocs: {
        description: "Find more info here",
        url: "https://github.com/fmenis/fastify-core-starter",
      },
      servers:
        fastify.config.APP_ENV === APP_ENV.LOCAL
          ? [
              {
                url: `http://localhost:${fastify.config.SERVER_PORT}`,
                description: "Service api",
              },
            ]
          : [
              {
                url: `https://${fastify.config.API_DOMAIN}`,
                description: "Service api",
              },
            ],
      tags: [
        { name: "auth", description: "Auth related end-points" },
        { name: "misc", description: "Misc related end-points" },
        { name: "accounts", description: "Accounts related end-points" },
      ].sort((a, b) => a.name.localeCompare(b.name)),
      components: {
        headers: {
          "x-request-id": {
            schema: { type: "string" },
            description:
              "Unique request identifier generated by the server. Include in support requests to trace logs.",
          },
        },
      },
    },
    transformObject: documentObject => {
      // add x-request-id doc for every response
      const { openapiObject } = documentObject as {
        openapiObject: Record<string, any>;
      };
      const apiPaths = Object.values(openapiObject.paths ?? {});

      for (const path of apiPaths) {
        const operations = Object.values(path as Record<string, any>);
        for (const operation of operations) {
          if (operation.responses) {
            for (const response of Object.values(
              operation.responses as Record<string, any>,
            )) {
              if (response && !("$ref" in response)) {
                response.headers = {
                  ...response.headers,
                  "x-request-id": {
                    $ref: "#/components/headers/x-request-id",
                  },
                };
              }
            }
          }
        }
      }

      return openapiObject;
    },
  });

  await fastify.register(fastifySwaggerUi, {
    routePrefix: "/doc",
    uiConfig: {
      docExpansion: "list",
      deepLinking: false,
    },
  });
}

export default fp(swaggerPlugin, { name: "swagger" });
